### ISSUE TITLE
Personal website

### ISSUE THREAD

**Issue by Ein-Tim** [Ein-Tim/Ein-Tim#3]

**Comment by Ein-Tim** [comment]
https://user-images.githubusercontent.com/67682506/166636396-ebc11947-3af8-453c-ae2d-dee26a7fa37b.MOV

**Comment by mmtmn** [comment]
Hey, congratulations on becoming a contributor to the Evals repository! Would love to chat sometime, not sure where to reach you tho

**Comment by Ein-Tim** [comment]
You can always shoot me a Twitter DM. My Twitter is linked in the GitHub bio.
